In [ ]:
import numpy as np
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
b=np.arange(2,52,2)
print(b)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [ ]:
#random ---->sub-package of numpy
A=np.random.rand(8,4)# Rand-range is between 0 and 1
print(A)

[[0.93887229 0.23607184 0.8060085  0.40317633]
 [0.80129839 0.14565964 0.47868341 0.03808412]
 [0.34902355 0.91868166 0.7166051  0.86644585]
 [0.19432883 0.83892177 0.15450707 0.07922433]
 [0.85571647 0.07677038 0.59370158 0.93574612]
 [0.23369121 0.57438629 0.74814598 0.23420273]
 [0.22697672 0.14786639 0.63446804 0.08928917]
 [0.79606208 0.71524536 0.73940375 0.84751614]]


In [ ]:
B=10*np.random.rand(4,2)
print(B)

[[3.97616804 4.01650212]
 [5.89536189 5.13010869]
 [8.47856274 0.73672966]
 [5.92512628 4.50044426]]


In [ ]:
C=np.floor(10*np.random.rand(8,4))
print(C)

[[5. 4. 5. 1.]
 [9. 8. 5. 5.]
 [5. 0. 1. 5.]
 [4. 9. 1. 1.]
 [0. 9. 0. 4.]
 [6. 4. 6. 6.]
 [3. 1. 4. 0.]
 [6. 7. 0. 8.]]


In [ ]:
#split it after 2 row and 5 row
print(np.vsplit(C,(2,5)))

[array([[5., 4., 5., 1.],
       [9., 8., 5., 5.]]), array([[5., 0., 1., 5.],
       [4., 9., 1., 1.],
       [0., 9., 0., 4.]]), array([[6., 4., 6., 6.],
       [3., 1., 4., 0.],
       [6., 7., 0., 8.]])]


In [ ]:
D=np.arange(1,33).reshape(4,8)
print(D)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
print(np.hsplit(D,(2,5)))

[array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]]), array([[ 3,  4,  5],
       [11, 12, 13],
       [19, 20, 21],
       [27, 28, 29]]), array([[ 6,  7,  8],
       [14, 15, 16],
       [22, 23, 24],
       [30, 31, 32]])]


In [ ]:
np.pi

3.141592653589793

In [ ]:
E=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(E)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
#convert rad to deg
F=np.rad2deg(E)
print(F)

[ 45.  60.  90. 180.]


In [ ]:
#convert deg to radians
G=np.deg2rad(F)
print(G)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
a=np.sin(1)
b=np.cos(1)
c=np.tan(1)
print("\n",a,"\n",b,"\n",c)


 0.8414709848078965 
 0.5403023058681398 
 1.5574077246549023


**Statistics**

In [ ]:
st=np.array([23,45,67,89,21,34])
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
np.std(st)


24.452334585202017

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
#It is also a sub-package of numpy
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax((C)))

23


In [ ]:
d=np.floor(10*np.random.rand(24).reshape(6,4))
print(d)

[[4. 1. 1. 3.]
 [5. 9. 0. 9.]
 [2. 8. 9. 4.]
 [8. 0. 5. 9.]
 [7. 7. 1. 4.]
 [4. 5. 3. 1.]]


In [ ]:
print(np.argmax((d)))

5


In [ ]:
d=10*np.random.rand(24).reshape(6,4)
print(d)

[[1.6370634  2.49671051 8.74636868 4.14693707]
 [2.65102636 8.7721782  0.6769456  2.37128702]
 [8.29192784 1.59748448 0.11399465 5.02179691]
 [9.56383145 9.8022004  3.81597633 1.36015799]
 [5.19566718 5.16255699 2.50861428 9.09594633]
 [2.01781859 8.16581249 3.85218969 7.35295323]]


In [ ]:
print(np.argmax(d,axis=0))

[3 3 0 4]


In [ ]:
print(np.argmin(d))

10


In [ ]:
print(np.argmin(d,axis=0))

[0 2 2 3]


In [ ]:
print(np.argmin(d,axis=1))

[0 2 2 3 2 0]


searching

In [ ]:
#FIND THE INDEXES WHERE THE VALUES ARE ODD
a=np.array([34,56,17,88,91])
b=np.where(a%2!=0)
print(b)

(array([2, 4]),)


In [ ]:
arr[b]

array([50, 67])

In [ ]:
#FINDING INDEXES WHERE THE VALUES ARE DIVISIBLE BY 6
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))


(array([0, 4, 5]),)


In [ ]:
# FINDING INEX NUMBER OF GIVEN NUMBER
 c=np.array([6,7,8,9,10])
x=np.searchsorted(c,10)
print(x)

4


In [ ]:
c=np.array([6,7,8,9,10])
x=np.searchsorted(c,6)
print(x)

0


In [ ]:
c=np.array([6,7,8,9,10])
x=np.searchsorted(c,7)
print(x)

1


In [ ]:
c=np.array([6,5,8,2,10])
x=np.searchsorted(c,5)
print(x)#GIVING WRONG OUTPUT

0


In [ ]:
#SORTING ARRAY
arr=np.array(['lavanya','prsanna','sasi','akhila'])
print(np.sort(arr))

['akhila' 'lavanya' 'prsanna' 'sasi']


In [ ]:
arr=np.array(['true','false','true'])
print(np.sort(arr))

['false' 'true' 'true']


In [ ]:
#2D SORT HAPPENS WITHIN THE ROW
arr=np.array([[12,40,34],[50,10,20]])
print(np.sort(arr))

[[12 34 40]
 [10 20 50]]


In [ ]:
#ARRAY FILTER
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]#FILTER LIST
newarr=arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
# TO ADD TWO ARRAYS
names=np.array(['lavanya','sasi','prasanna','akhila'])
initials=np.array(['P','P','N','T'])
for i,j in zip(initials,names):
  print(i,".",j)

P . lavanya
P . sasi
N . prasanna
T . akhila


In [ ]:
#ADD THREE ARRAYS
names=np.array(['lavanya','sasi','prasanna','akhila'])
initials=np.array(['P','P','N','T'])
num=np.array(['05b1','05b0','05a6','o5c0'])
for i,j,k in zip(initials,names,num):
  print(i,".",j,".",k)

P . lavanya . 05b1
P . sasi . 05b0
N . prasanna . 05a6
T . akhila . o5c0


In [ ]:
a1=np.array([10,30,40,50,60])
a2=np.array([2,3,4,5,6])
n=np.multiply(a1,a2)
print(n)

[ 20  90 160 250 360]


In [ ]:
a1=np.array([10,30,40,50,60])
a2=np.array([2,3,4,5,6])
m=np.divide(a1,a2)
print(m)

[ 5. 10. 10. 10. 10.]


In [ ]:
a1=np.array([10,30,40,50,60])
a2=np.array([2,3,4,5,6])
o=np.mod(a1,a2)
print(o)

[0 0 0 0 0]


In [ ]:
a1=np.array([10,30,40,50,60])
a2=np.array([2,3,4,5,6])
p=np.divmod(a1,a2)
print(p)

(array([ 5, 10, 10, 10, 10]), array([0, 0, 0, 0, 0]))


**logarithms**

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log10(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
#NATURAL log e
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
#log base 2
print(np.log2(a))

0.2630344058337938


In [ ]:
#log base 10
print(np.log10(a))

0.07918124604762482


In [ ]:
b=np.array([1,1,1,2,3,4])
print(np.log(b))

[0.         0.         0.         0.69314718 1.09861229 1.38629436]


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumprod(a2)#MULTIPLY FIRST NUMBER AND SECOUND NUMBER
print(x)

[   5   30  210 2100]


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumsum(a2)#ADDIND FIRST NUMBER AND SECOUND NUMBER
print(x)

[ 5 11 18 28]


In [ ]:
a3=np.array([10,15,52,15])
newarr=np.diff(a3)# SUNSTRACTING SECOUND NUMBER FROM FIRST NUMBER
print(newarr)

[  5  37 -37]


In [ ]:
#FINDING LCM
m1=455
m2=665
x=np.lcm(m1,m2)
print(x)

8645


In [ ]:
#FINDING GCD
m1=455
m2=665
x=np.gcd(m1,m2)
print(x)

35


In [ ]:
#TAKE MULTIPLE INPUTS GIVES SINGLE OUTPUT
a=np.array([12,15,60])
gc=np.gcd.reduce(a)
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a)
print(lc)

60
