In [ ]:
#importing
import numpy as np


Arrays


In [ ]:
#creating 1D array
import numpy as np
a=np.array([2,3,4,5,])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#craeting 2D array-rows and colums
import numpy as np
b=np.array([[2,3,4],[7,8,9]])
print(b)

[[2 3 4]
 [7 8 9]]


In [ ]:
#craeting a 3D array--rows,colums,groups
import numpy as np
c=np.array([[[1,2,3],[4,5,6]],[[6,9,0],[2,3,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  9  0]
  [ 2  3 11]]]


In [ ]:
#checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

2
2
3


In [ ]:
#ones
import numpy as np
d=np.ones((2,5))#2D#rows,columns
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#ones
import numpy as np
e=np.ones((2,3,2))#3D groups ,rows ,columns
print(e)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#zeros
import numpy as np
f=np.zeros((3,2))#2D#rows ,columns
print(f)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#zreos
import numpy as np
g=np.zeros((2,3,2))#groups ,rows,colums #3D
print(g)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
import numpy as np
h=np.eye(2)
print(h)

[[1. 0.]
 [0. 1.]]


In [ ]:
#arrange
import numpy as np
i=np.arange(3,31,3)#printing from 3 to 30 by dividing 3
print(i)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#reshape
import numpy as np
j=np.arange(3,31,3).reshape(5,2)
print(j)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
#5 table
import numpy as np
k=np.arange(5,1001,5)
print(k)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
import numpy as np
l=np.arange(5,1001,5).reshape(40,5)
print(l)

[[   5   10   15   20   25]
 [  30   35   40   45   50]
 [  55   60   65   70   75]
 [  80   85   90   95  100]
 [ 105  110  115  120  125]
 [ 130  135  140  145  150]
 [ 155  160  165  170  175]
 [ 180  185  190  195  200]
 [ 205  210  215  220  225]
 [ 230  235  240  245  250]
 [ 255  260  265  270  275]
 [ 280  285  290  295  300]
 [ 305  310  315  320  325]
 [ 330  335  340  345  350]
 [ 355  360  365  370  375]
 [ 380  385  390  395  400]
 [ 405  410  415  420  425]
 [ 430  435  440  445  450]
 [ 455  460  465  470  475]
 [ 480  485  490  495  500]
 [ 505  510  515  520  525]
 [ 530  535  540  545  550]
 [ 555  560  565  570  575]
 [ 580  585  590  595  600]
 [ 605  610  615  620  625]
 [ 630  635  640  645  650]
 [ 655  660  665  670  675]
 [ 680  685  690  695  700]
 [ 705  710  715  720  725]
 [ 730  735  740  745  750]
 [ 755  760  765  770  775]
 [ 780  785  790  795  800]
 [ 805  810  815  820  825]
 [ 830  835  840  845  850]
 [ 855  860  865  870  875]
 [ 880  885  890  89

In [ ]:
#linespace
import numpy as np
m=np.linspace(1,2,6)#split the numbers from 1 to 2 until 6 numbers
print(m)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
import numpy as np
n=np.arange(1,7).reshape(2,3)
print(n)
o=np.arange(9,15).reshape(2,3)
print(o)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(n+o)

[[10 12 14]
 [16 18 20]]


In [ ]:
#using sum
p=np.sum((n,o))
print(p)

90


In [ ]:
q=np.sum((n,o),axis =0)
print(q)

[[10 12 14]
 [16 18 20]]


In [ ]:
r=np.sum((n,o),axis =1)
print(r)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
s=np.sum((n,o),axis =2)
print(s)

[[ 6 15]
 [30 39]]


In [ ]:
t=np.ones((4,2))
u=np.ones((4,2))
print(np.sum((t,u),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A+B)
print(A*B)

[[3 1]
 [3 5]]
[[2 0]
 [0 4]]


In [ ]:
print(A@B)

[[5 4]
 [3 4]]


b=np.array[25.89,361.81] #find square roots and iterate through result values output:5 square is 25

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square is ",i)

5.0 square is  25
17.0 square is  289
19.0 square is  361
9.0 square is  81


array joins

In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(a)
print(b)

[[34 35 36]
 [37 38 39]]
[[4 5 6]
 [7 8 9]]


In [ ]:
c=np.arange(30).reshape(2,3,5)
print(c)
print("\n")
print(np.dstack(c))
#number of rows become number of columns
#column become rows
#group become colums

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
